### PR TITLE
Behavior boot xhyve

### PR DESCRIPTION
**Pull request by zchee**
@nathanleclaire
Finished behavior booting xhyve and first connection ssh!
but, So dirty, I would later rebase.
# 
### Issues and help!

For now, execute xhyve use gorutine.
If not use gorutine, stopped work at point of execute xhyve.

But, gorutine is closed along with the main thread.
Will need change to `syscall fork` or `go execute external process myself` or `OS X launchd daemon` or other daemonize method.
Also, @tiborvass said use reexec docker core package. https://github.com/tiborvass/xhyve-bindings#roadmap
If true, it should implement the vm control to xhyve...
Do you have any good or other ideas?

And, Shared folder issue.
Although I think that it is for the time being may be use the nfs.
However, technology that enables the shared folder does not know only `libvirt`.
Do you have knowledge of other shared folder method?

I will later commit for a little customized `boot2docker.iso` source.
# 
### Changed

I think you quickly understand that if you read the code, but I write for other guys saw repo.
#### Definitely exec xhyve

So far, Use `os/exec`package, `exec.Command` func for execute xhyve binary.
but, cause I do not know, In fact xhyve does not seem to launch.
On the proof, `/var/db/dhcpd_leases` is not created.

So, I've embedded a [tiborvass/xhyve-bindings](https://github.com/tiborvass/xhyve-bindings) that tiborvass developed. Thanks @tiborvass :)
Repository becomes larger, and will need `cgo` build, but the flexibility is handed Because xhyve source include.
Fork process, Daemonize, and more.
#### xhyve headless mode

Remove `stdio` flag in this kexec command.

``` bash
-s 0:0,hostbridge -s 31,lpc -s 0:0,hostbridge -l com1,stdio
# to
-s 0:0,hostbridge -s 31,lpc -s 0:0,hostbridge -l com1
```

Then, xhyve will not output to `stdin`.
Together, it has disappeared login screen. Successful autologin `docker` user need not be input `tcuser` password.
but, May be need a customize boot2docker `bootscript.sh`. Does not yet verification.
#### Copy inside xhyve the including publicSSHKey userdata.tar

xhyve still does not implement a shared folder and vmware like `CopyFileFromHostGuest` `runScriptInGuest` commands.
So, mounting `/dev/vdb` use `virtio-blk` interface.

``` bash
-s 5,virtio-blk, userdata.tar
```

`-5` flag is mounting `/dev/vdb`.
Then, customized `bootscript.sh` will export to /var/lib/boot2docker/userdata.tar If `/dev/vdb` is not empty.
This hack is too bad. Is likely there are other ways.
#### Disable Blank diskimage overwride `boot2docker.iso`

`generateBlankDiskImage()` func is overwride `boot2docker.iso`.
`boot2docker.iso` is for pci cd boot image. Do not overwride.
It's what I wrote previous. Sorry :(
#### Disable tuntap

For now, Disable tuntap virtual network protocol for easy develop and debug.
The better performance, it will later enable.
#### Enable ACPI

xhyve supported ACPI interface now. So enable default.
#### Get Machine IP in `dhcpd_leases` from MAC address

xhyve is always outputing dhcp data in `dhcpd_leases`.
So, Get the IP of the machine that trying to launch now, use the `uuid2mac` written by @ailispaw.
See https://github.com/ailispaw/boot2docker-xhyve/tree/master/uuid2ip
# 

I'm sorry a very incomprehensible English.
It is very better than of writing in English to write program... :scream:

### CODE REVIEW

**Comment by tiborvass** [comment]
Wow man thanks :D I'll let @nathanleclaire comment on the content

**Comment by zchee** [comment]
@tiborvass Thanks!
I had realized that xhyve is not able to exec, the xhyve-bindings it was very helped.
and, I've embedded without import. sorry.

Thanks again.

**Comment by nathanleclaire** [comment]
Whoa nice.  It will take some time to take a look but I will when I get a chance.

**Comment by zchee** [comment]
@nathanleclaire thanks.
I pushed custom boot2docker.

# 

Edit
Rename branch.
and, delete unnecessary hack
See https://github.com/zchee/boot2docker-legacy/tree/xhyve and please build.

**Comment by zchee** [comment]
## Update

Get Machine IP use embedded vmnet packages instead of execute `uuid2mac` binary
Thanks for advice and vmnet packages @ailispaw

## Resolve daemonizes issue

For now, successful `docker-machine create` command. Also, `ssh`, `env`.
However, it is not a good feel.
Very dirty, it is not pretty.

Use...
- This PR `behavior-boot-xhyve` branch.
  - Since it is was hard to exec itself that embedded `xhyve.Exec`, for the time being, is separated into xhyve-bindings.
  - `vmnet` framework required `sudo`. Avoid use set root user id
- https://github.com/zchee/xhyve-bindings/tree/daemonize
  - Exec itself use gorutine. Provisional binary name `goxhyve`
- https://github.com/zchee/boot2docker-legacy/tree/xhyve
  - Copy inside xhyve the including publicSSHKey userdata.tar

embedded way is better, or separate way is good, I want advice.

Since now was supposed to work, wait for your advice.

### Notice

When the docker-machine-xhyve was `os.exec` the xhyve-bindings, it did not work in the same way that does not work `os.exec` xhyve binary.
but, xhyve-bindings are execute itself using gorutine, it worked.
https://github.com/zchee/xhyve-bindings/blob/daemonize/main/main.go#L45-L52

**Comment by nathanleclaire** [comment]
@zchee Would you like to carry this in the master branch of your repository?  I am unable to devote any real attention to it at the moment.

**Comment by tiborvass** [comment]
@zchee as far as xhyve-bindings is concerned, feel free to send PRs to my repo.

**Comment by zchee** [comment]
@nathanleclaire OK!!
You are busy with other work, I knew.
Thiis PR are carry to my repository. will Close PR.

So, If it's alright with you, that it is easy to understand the other person, also In order to prevent the unnecessary issue post to your repo, I am glad when willing to write encourage to my repo a short infomation in the README :)
I guess because not been attention lol

@tiborvass OK. I will send PR to your repository.
Now, I Implemented a simple daemon, but there is little more improvement plan.
Whether it is better to have sent at once? Or it is better that sent small?

**Comment by nathanleclaire** [comment]
> So, If it's alright with you, that it is easy to understand the other person, also In order to prevent the unnecessary issue post to your repo, I am glad when willing to write encourage to my repo a short infomation in the README :)
> I guess because not been attention lol

If I'm understanding you correctly (writing some documentation for the plugin in your repository?), then go for it! :)

**Comment by nathanleclaire** [comment]
@zchee If/when you are ready to assume primary responsibility in your repo, let me know and I will link to it from mine.

**Comment by zchee** [comment]
@nathanleclaire 

> If/when you are ready to assume primary responsibility in your repo, let me know and I will link to it from mine.

Yes, correct. Thanks:)
and Now, merge to my master branch.
Ready!

**Comment by zchee** [comment]
@nathanleclaire 

> If/when you are ready to assume primary responsibility in your repo, let me know and I will link to it from mine.

When you have finished, Could you close PR?

**Comment by nathanleclaire** [comment]
Yep

**Pull request closed without merging**
